### ISSUE TITLE
How good is the ghostvlad weights of the model?

### ISSUE THREAD

**Issue by fazlekarim** [taylorlu/Speaker-Diarization#12]
How good are the weights to the ghostvlad model? Do I need to train it some more or the weights are the ones presented by the authors in their paper? Did you verify this?

**Comment by taylorlu** [comment]
Just a pretrained model, I haven't verify it, you had better retrain it.

**Comment by fazlekarim** [comment]
Did you use the weights from: https://github.com/WeidiXie/VGG-Speaker-Recognition or did you retrain it yourself on your re-implementation (https://github.com/taylorlu/ghostvlad-speaker)?

**Comment by taylorlu** [comment]
The 2 models' weights are the same, I haven't retrained.
