### ISSUE TITLE
How to caculate DER, EER ?

### ISSUE THREAD

**Issue by tranquangchung** [taylorlu/Speaker-Diarization#25]
Hello!

Thank you @taylorlu  for all your work here.
I am researching on speaker diarization. I have done all tutorial from you, but i don't know how to evaluation EER, DER.
Can you support me to create ground trust and code to evaluation ?
Thank you

**Comment by taylorlu** [comment]
You mean Diarization Error Rate(DER) and Equal Error Rate(EER)?
You can refer to [SimpleDER](https://github.com/wq2012/SimpleDER) and [VGG-Speaker-Recognition](https://github.com/WeidiXie/VGG-Speaker-Recognition) for more details.

**Comment by tranquangchung** [comment]
thank you, 2 projects you refer very useful for me
