### ISSUE TITLE
How can I resolve 'killed' problem?

### ISSUE THREAD

**Issue by nyongja** [taylorlu/Speaker-Diarization#26]
I generated speaker embeddings to use 4 persons audio data you provided.
And I tried "python train.py" but  it says Killed in the terminial.
How can I resolve this problem..?

**Comment by taylorlu** [comment]
The speaker embeddings should contain a huge dataset like VCTK, the 4 persons audio example only shows how to predict or generate speaker embedding by GhostVLAD model.
