### ISSUE TITLE
About final output

### ISSUE THREAD

**Issue by xiaozhi2015** [taylorlu/Speaker-Diarization#27]
![image](https://user-images.githubusercontent.com/12682406/71164482-23392400-228a-11ea-9991-7062109337a4.png)

Could every output label match the target people of openSLR?

**Comment by xiaozhi2015** [comment]
@taylorlu   If I build a lib of target people, can I match the output label with my lib?

**Comment by taylorlu** [comment]
No, the index of the output speaker is start of zero, and the diarization cannot recognize the origin speaker since the embeddings of each sliding window become more continuous rather than discrete as the training speakers.

**Comment by xiaozhi2015** [comment]
OK，thx!
