### ISSUE TITLE
pre-shifted predicted sequence

### ISSUE THREAD

**Issue by gogyzzz** [taylorlu/Speaker-Diarization#3]
Hello, I'm testing your framework on my testset.

I did below with the pretrained model on your repository.
utterances -> webrtcvad -> get (start,end) pair -> concatenate utterances randomly

I think there are some time alignment issue. 
But when I use dvector based embedder, there are no such issue.

![image](https://user-images.githubusercontent.com/8141431/57746475-4d32d280-770c-11e9-8135-fbadb9006402.png)

**Comment by taylorlu** [comment]
Well, the dvector is based on rnn module, which can output at every timestep, but ghostvlad is based on cnn, it must slide a little far such as 500ms to gen a embedding, so it may have a slight shift.
