### ISSUE TITLE
What is SRC_PATH & data_path ?

### ISSUE THREAD

**Issue by zeyuanchen23** [taylorlu/Speaker-Diarization#4]
Hi!

In [generate_embeddings.py](https://github.com/taylorlu/Speaker-Diarization/blob/master/ghostvlad/generate_embeddings.py), there is an argument named *data_path*, but it seems that it is never used. There is another hardcoded variable called SRC_PATH. Should we change it to the path to our dataset (i.e. the directory containing .wav files, such as ST-CMDS-20170001_1-OS in the [openslr](http://www.openslr.org/38))?

**Comment by taylorlu** [comment]
Yes, I forgot to remove the test code, `SRC_PATH` has the same meaning of `args.data_path`
