### ISSUE TITLE
Misalignment? 

### ISSUE THREAD

**Issue by zeyuanchen23** [taylorlu/Speaker-Diarization#5]
Hi!

I made a synthetic test .wav file by concatenating utterances of person _a_ and _b_ from your [4persons sample dataset](https://github.com/taylorlu/Speaker-Diarization/tree/master/ghostvlad/4persons). However, it seems that there is some misalignment in the visualization. For instance, the model only predicts the speakers from 0 sec to 16.216 sec, but there is around 17.513s in the audio (please see the attached file
[sample_2persons.zip](https://github.com/taylorlu/Speaker-Diarization/files/3199804/sample_2persons.zip)
).

Is it because of some alignment issues in the model / visualization? Or because the CNN embeddings were used? Is there any way to fix this issue?

Thanks!

**Comment by taylorlu** [comment]
Simply caused by the last vad slice was not taken into consideration.
