### ISSUE TITLE
train.py: allow_pickle

### ISSUE THREAD

**Issue by zeyuanchen23** [taylorlu/Speaker-Diarization#6]
Hi! 

Found a minor issue in the [train.py](https://github.com/taylorlu/Speaker-Diarization/blob/master/train.py).

Got an error `Object arrays cannot be loaded when allow_pickle=False ` at [line 38](https://github.com/taylorlu/Speaker-Diarization/blob/403783173239a33bfd4de0774921ba9479413641/train.py#L38). This issue can be solved by changing this line to:

`train_data = np.load('./ghostvlad/training_data.npz', allow_pickle=True)`

Please refer to the [demo code of uisrnn](https://github.com/google/uis-rnn/blob/bc958fca1cb939053f47c6f0f93076e3337a0c12/demo.py#L38) for more details.

**Comment by taylorlu** [comment]
Yes, there are some trifles exist in the codes, hope to have time to fix it.
